In [112]:
import pandas as pd
import matplotlib.ticker as mtick
import numpy as np
from arcgis.gis import *
gis = GIS()

In [113]:
#Layer name for K-12 enrollment data
lyrK12 = "Utah_Schools_PreK_to_12"

sdfK12 = pd.DataFrame.spatial.from_featureclass(lyrK12)
sdfK12.columns

Index(['FID', 'OBJECTID', 'LEAName', 'SchoolName', 'LEANumber', 'LEAID',
       'SchoolID', 'SchoolNumb', 'CharterSch', 'PrivateSch', 'OnlineScho',
       'NESS', 'GradeLow', 'GradeHigh', 'SchoolLeve', 'SchoolType', 'Address',
       'City', 'State', 'ZipCode', 'FederalLoc', 'PhoneNumbe', 'Website',
       'DateOpened', 'DateClosed', 'SchoolYear', 'LEATYPE', 'TotalK12', 'K',
       'Grade1', 'Grade2', 'Grade3', 'Grade4', 'Grade5', 'Grade6', 'Grade7',
       'Grade8', 'Grade9', 'Grade10', 'Grade11', 'Grade12', 'Female', 'Male',
       'AmericanIn', 'Black', 'Asian', 'Hispanic', 'MultipleRa', 'PacificIsl',
       'White', 'Economical', 'EnglishLea', 'StudentDis', 'Homeless',
       'Preschool', 'SHAPE'],
      dtype='object')

In [114]:
#initial look at data
sdfK12

       FID  ...                                              SHAPE
0        0  ...  {"x": -111.876144388118, "y": 40.3939967341324...
1        1  ...  {"x": -111.84812433271, "y": 40.4260338346788,...
2        2  ...  {"x": -111.912913356165, "y": 40.3493043906936...
3        3  ...  {"x": -111.733244642649, "y": 40.2785450636399...
4        4  ...  {"x": -111.663892720134, "y": 40.2568433920116...
...    ...  ...                                                ...
1237  1237  ...  {"x": -111.392561118769, "y": 40.496820150236,...
1238  1238  ...  {"x": -112.002411963542, "y": 41.2439917321969...
1239  1239  ...  {"x": -112.000463561709, "y": 41.3179164079397...
1240  1240  ...  {"x": -112.052520442842, "y": 41.3223705145609...
1241  1241  ...  {"x": -111.631390191832, "y": 40.1548064594199...

[1242 rows x 56 columns]

In [115]:
sdfK12.groupby(['SchoolLeve','PrivateSch','CharterSch','OnlineScho'], as_index=False).agg(
                                                                                          K  =('K'       ,'sum'),
                                                                                          G01=('Grade1'  ,'sum'),
                                                                                          G02=('Grade2'  ,'sum'),
                                                                                          G03=('Grade3'  ,'sum'),
                                                                                          G04=('Grade4'  ,'sum'),
                                                                                          G05=('Grade5'  ,'sum'),
                                                                                          G06=('Grade6'  ,'sum'),
                                                                                          G07=('Grade7'  ,'sum'),
                                                                                          G08=('Grade8'  ,'sum'),
                                                                                          G09=('Grade9'  ,'sum'),
                                                                                          G10=('Grade10' ,'sum'),
                                                                                          G11=('Grade11' ,'sum'),
                                                                                          G12=('Grade12' ,'sum'),
                                                                                          Tot=('TotalK12','sum'))

   SchoolLeve PrivateSch CharterSch OnlineScho  ...    G10    G11    G12     Tot
0        ELEM                                   ...     83    109     85  290424
1        ELEM                                Y  ...      0      0      0     187
2        ELEM                     Y             ...      0      0      0   28123
3        ELEM          Y                        ...      0      0      0       0
4        HIGH                                   ...  46582  45057  43102  159154
5        HIGH                                Y  ...     93    134    132     464
6        HIGH                     Y             ...   2054   2018   1718    9889
7        HIGH                     Y          Y  ...    243    235    169    1306
8        HIGH          Y                        ...      0      0      0       0
9        HIGH          Y                     Y  ...      0      0      0       0
10        K12                                   ...    127    252    916    1891
11        K12                                Y  ...      4      4      3    2600
12        K12                     Y             ...    861    759    678   12030
13        K12                     Y          Y  ...    379    429    363    3281
14        K12          Y                        ...      0      0      0       0
15        K12          Y                     Y  ...      0      0      0       0
16        MID                                   ...      2      0      0  127774
17        MID                                Y  ...      0      0      0    3093
18        MID                     Y             ...      0      0      0   14135
19        MID          Y                        ...      0      0      0       0
20        MID          Y                     Y  ...      0      0      0       0
21       NONE                                   ...      0      0      0       0
22       NONE          Y                        ...      0      0      0       0
23       PREK                                   ...      0      0      0       0
24       PREK          Y                        ...      0      0      0       0
25       PREK          Y                     Y  ...      0      0      0       0

[26 rows x 18 columns]

In [195]:
#created filtered dataset that removes unnecessary rows

#display total number of schools in original datset
display ("Total Schools: " + str(sdfK12.shape[0]))

sdfK12_filtered = sdfK12.copy()

#remove NONE and PREK schools, since no data
sdfK12_filtered = sdfK12_filtered[(sdfK12_filtered['SchoolLeve'] != 'PREK') & (sdfK12_filtered['SchoolLeve'] != 'NONE')]
display ("Total Schools After NONE/PREK Removed: " + str(sdfK12_filtered.shape[0]))

#remove online schools
sdfK12_filtered = sdfK12_filtered[sdfK12_filtered['OnlineScho'] != 'Y']
display ("Total Schools After Online Removed: " + str(sdfK12_filtered.shape[0]))

#inlcude only desired columns
sdfK12_filtered = sdfK12_filtered[['FID','OBJECTID', 'LEAName', 'SchoolName',
                                   'CharterSch', 'PrivateSch', 'OnlineScho',
                                   'GradeLow', 'GradeHigh', 'SchoolLeve', 'SchoolType', 'TotalK12', 'K',
                                   'Grade1', 'Grade2', 'Grade3', 'Grade4', 'Grade5', 'Grade6', 'Grade7',
                                   'Grade8', 'Grade9', 'Grade10', 'Grade11', 'Grade12','SHAPE']]



display ("Total Filtered Enrollment: " + str(sdfK12_filtered['TotalK12'].sum()))

display(sdfK12_filtered)

'Total Schools: 1242'

'Total Schools After NONE/PREK Removed: 1176'

'Total Schools After Online Removed: 1155'

'Total Filtered Enrollment: 643420'

       FID  ...                                              SHAPE
0        0  ...  {"x": -111.876144388118, "y": 40.3939967341324...
1        1  ...  {"x": -111.84812433271, "y": 40.4260338346788,...
2        2  ...  {"x": -111.912913356165, "y": 40.3493043906936...
3        3  ...  {"x": -111.733244642649, "y": 40.2785450636399...
4        4  ...  {"x": -111.663892720134, "y": 40.2568433920116...
...    ...  ...                                                ...
1237  1237  ...  {"x": -111.392561118769, "y": 40.496820150236,...
1238  1238  ...  {"x": -112.002411963542, "y": 41.2439917321969...
1239  1239  ...  {"x": -112.000463561709, "y": 41.3179164079397...
1240  1240  ...  {"x": -112.052520442842, "y": 41.3223705145609...
1241  1241  ...  {"x": -111.631390191832, "y": 40.1548064594199...

[1155 rows x 26 columns]

In [156]:
#Set private and charter schools to PriCha group
sdfK12_filtered.loc[((sdfK12_filtered['PrivateSch']=='Y')),'Group'] = 'PriCha'
sdfK12_filtered.loc[((sdfK12_filtered['CharterSch']=='Y')),'Group'] = 'PriCha'
sdfK12_filtered.loc[((sdfK12_filtered['PrivateSch']!='Y') & (sdfK12_filtered['CharterSch']!='Y')),'Group'] = 'Public'

#add new Level column
sdfK12_filtered['School_Level'] = sdfK12_filtered['SchoolLeve'] 

sdfK12_filtered.groupby(['Group'], as_index=False).agg(NumSchools=('TotalK12','size'))

    Group  NumSchools
0  PriCha         272
1  Public         883

In [157]:
gradesums = sdfK12_filtered.groupby(['School_Level','Group'], as_index=False).agg(K  =('K'      ,'sum'),
                                                                       G01=('Grade1' ,'sum'),
                                                                       G02=('Grade2' ,'sum'),
                                                                       G03=('Grade3' ,'sum'),
                                                                       G04=('Grade4' ,'sum'),
                                                                       G05=('Grade5' ,'sum'),
                                                                       G06=('Grade6' ,'sum'),
                                                                       G07=('Grade7' ,'sum'),
                                                                       G08=('Grade8' ,'sum'),
                                                                       G09=('Grade9' ,'sum'),
                                                                       G10=('Grade10','sum'),
                                                                       G11=('Grade11','sum'),
                                                                       G12=('Grade12','sum'),
                                                                       Tot=('TotalK12','sum'))

display(gradesums)

  School_Level   Group      K    G01    G02  ...    G09    G10    G11    G12     Tot
0         ELEM  PriCha   3829   3893   3719  ...    165      0      0      0   28123
1         ELEM  Public  40750  42469  41674  ...     53     83    109     85  290424
2         HIGH  PriCha      0      0      0  ...   1920   2054   2018   1718    9889
3         HIGH  Public    420    354    318  ...  20357  46582  45057  43102  159154
4          K12  PriCha    878    909    887  ...   1070    861    759    678   12030
5          K12  Public     55     46     51  ...     95    127    252    916    1891
6          MID  PriCha   1464   1493   1406  ...    809      0      0      0   14135
7          MID  Public      0      0      0  ...  26465      2      0      0  127774

[8 rows x 16 columns]

In [158]:
#check ELEM schools with 8+ enrollment
sdfK12_filtered.loc[((sdfK12_filtered['School_Level']=='ELEM') & (sdfK12_filtered['Grade8']>0))]

       FID  OBJECTID  ...   Group School_Level
12      12        13  ...  PriCha         ELEM
15      15        16  ...  PriCha         ELEM
48      48        49  ...  PriCha         ELEM
90      90        91  ...  PriCha         ELEM
99      99       100  ...  PriCha         ELEM
106    106       107  ...  Public         ELEM
117    117       118  ...  PriCha         ELEM
119    119       120  ...  PriCha         ELEM
343    343       344  ...  Public         ELEM
433    433       434  ...  Public         ELEM
585    585       586  ...  PriCha         ELEM
625    625       626  ...  PriCha         ELEM
656    656       657  ...  PriCha         ELEM
727    727       728  ...  PriCha         ELEM
730    730       731  ...  PriCha         ELEM
733    733       734  ...  PriCha         ELEM
742    742       743  ...  PriCha         ELEM
751    751       752  ...  Public         ELEM
753    753       754  ...  PriCha         ELEM
816    816       817  ...  Public         ELEM
998    998       999  ...  PriCha         ELEM
1039  1039      1040  ...  PriCha         ELEM
1043  1043      1044  ...  PriCha         ELEM
1048  1048      1049  ...  PriCha         ELEM
1060  1060      1061  ...  Public         ELEM
1128  1128      1129  ...  PriCha         ELEM
1170  1170      1171  ...  PriCha         ELEM
1171  1171      1172  ...  PriCha         ELEM
1184  1184      1185  ...  PriCha         ELEM
1200  1200      1201  ...  PriCha         ELEM
1224  1224      1225  ...  PriCha         ELEM

[31 rows x 28 columns]

Most ELEM schools with Grade 8 enrollment > 0, stop at Grade 8 and have very little 9-12 enrollment. So, will set category for all ELEM schools with Grade 8 enrollment > 0 as K8.

In [159]:
#Elementary Schools with 8+ enrollment, classify as K-8
sdfK12_filtered.loc[(((sdfK12_filtered['SchoolLeve']=='ELEM') & (sdfK12_filtered['Grade8']>0)) | (sdfK12_filtered['SchoolLeve']=='MID') & (sdfK12_filtered['Grade4']>0)),'School_Level']='K8'
display(sdfK12_filtered[sdfK12_filtered['School_Level']=='K8'])

       FID  OBJECTID  ...   Group School_Level
9        9        10  ...  PriCha           K8
12      12        13  ...  PriCha           K8
15      15        16  ...  PriCha           K8
40      40        41  ...  PriCha           K8
48      48        49  ...  PriCha           K8
90      90        91  ...  PriCha           K8
99      99       100  ...  PriCha           K8
106    106       107  ...  Public           K8
117    117       118  ...  PriCha           K8
119    119       120  ...  PriCha           K8
343    343       344  ...  Public           K8
433    433       434  ...  Public           K8
546    546       547  ...  PriCha           K8
548    548       549  ...  PriCha           K8
581    581       582  ...  PriCha           K8
585    585       586  ...  PriCha           K8
625    625       626  ...  PriCha           K8
629    629       630  ...  PriCha           K8
634    634       635  ...  PriCha           K8
637    637       638  ...  PriCha           K8
656    656       657  ...  PriCha           K8
721    721       722  ...  PriCha           K8
727    727       728  ...  PriCha           K8
730    730       731  ...  PriCha           K8
733    733       734  ...  PriCha           K8
739    739       740  ...  PriCha           K8
742    742       743  ...  PriCha           K8
747    747       748  ...  PriCha           K8
751    751       752  ...  Public           K8
753    753       754  ...  PriCha           K8
816    816       817  ...  Public           K8
998    998       999  ...  PriCha           K8
1029  1029      1030  ...  PriCha           K8
1039  1039      1040  ...  PriCha           K8
1042  1042      1043  ...  PriCha           K8
1043  1043      1044  ...  PriCha           K8
1048  1048      1049  ...  PriCha           K8
1055  1055      1056  ...  PriCha           K8
1056  1056      1057  ...  PriCha           K8
1060  1060      1061  ...  Public           K8
1071  1071      1072  ...  PriCha           K8
1079  1079      1080  ...  PriCha           K8
1128  1128      1129  ...  PriCha           K8
1145  1145      1146  ...  Public           K8
1170  1170      1171  ...  PriCha           K8
1171  1171      1172  ...  PriCha           K8
1184  1184      1185  ...  PriCha           K8
1200  1200      1201  ...  PriCha           K8
1224  1224      1225  ...  PriCha           K8

[49 rows x 28 columns]

In [160]:
gradesums = sdfK12_filtered.groupby(['School_Level','Group'], as_index=False).agg(K  =('K'      ,'sum'),
                                                                       G01=('Grade1' ,'sum'),
                                                                       G02=('Grade2' ,'sum'),
                                                                       G03=('Grade3' ,'sum'),
                                                                       G04=('Grade4' ,'sum'),
                                                                       G05=('Grade5' ,'sum'),
                                                                       G06=('Grade6' ,'sum'),
                                                                       G07=('Grade7' ,'sum'),
                                                                       G08=('Grade8' ,'sum'),
                                                                       G09=('Grade9' ,'sum'),
                                                                       G10=('Grade10','sum'),
                                                                       G11=('Grade11','sum'),
                                                                       G12=('Grade12','sum'),
                                                                       Tot=('TotalK12','sum'))

display(gradesums)

  School_Level   Group      K    G01    G02  ...    G09    G10    G11    G12     Tot
0         ELEM  PriCha   2216   2188   2069  ...      0      0      0      0   13822
1         ELEM  Public  40640  42358  41568  ...     48     82    104     84  289425
2         HIGH  PriCha      0      0      0  ...   1920   2054   2018   1718    9889
3         HIGH  Public    420    354    318  ...  20357  46582  45057  43102  159154
4          K12  PriCha    878    909    887  ...   1070    861    759    678   12030
5          K12  Public     55     46     51  ...     95    127    252    916    1891
6           K8  PriCha   3077   3198   3056  ...    974      0      0      0   28028
7           K8  Public    110    111    106  ...      5      1      5      1    1008
8          MID  PriCha      0      0      0  ...      0      0      0      0     408
9          MID  Public      0      0      0  ...  26465      2      0      0  127765

[10 rows x 16 columns]

In [161]:
#check HIGH schools with Grade 8 enrollment > 0
sdfK12_filtered.loc[((sdfK12_filtered['School_Level']=='HIGH') & (sdfK12_filtered['Grade8']>0))]

       FID  OBJECTID  ...   Group School_Level
1        1         2  ...  Public         HIGH
5        5         6  ...  PriCha         HIGH
116    116       117  ...  PriCha         HIGH
133    133       134  ...  Public         HIGH
138    138       139  ...  Public         HIGH
160    160       161  ...  Public         HIGH
161    161       162  ...  Public         HIGH
261    261       262  ...  Public         HIGH
297    297       298  ...  Public         HIGH
340    340       341  ...  Public         HIGH
341    341       342  ...  Public         HIGH
351    351       352  ...  Public         HIGH
359    359       360  ...  Public         HIGH
408    408       409  ...  Public         HIGH
428    428       429  ...  Public         HIGH
459    459       460  ...  Public         HIGH
529    529       530  ...  Public         HIGH
542    542       543  ...  PriCha         HIGH
587    587       588  ...  PriCha         HIGH
605    605       606  ...  PriCha         HIGH
622    622       623  ...  PriCha         HIGH
664    664       665  ...  PriCha         HIGH
725    725       726  ...  Public         HIGH
741    741       742  ...  Public         HIGH
744    744       745  ...  PriCha         HIGH
745    745       746  ...  PriCha         HIGH
817    817       818  ...  Public         HIGH
820    820       821  ...  Public         HIGH
821    821       822  ...  Public         HIGH
840    840       841  ...  Public         HIGH
871    871       872  ...  Public         HIGH
872    872       873  ...  Public         HIGH
924    924       925  ...  Public         HIGH
992    992       993  ...  Public         HIGH
993    993       994  ...  Public         HIGH
1017  1017      1018  ...  PriCha         HIGH
1155  1155      1156  ...  Public         HIGH
1157  1157      1158  ...  PriCha         HIGH
1164  1164      1165  ...  Public         HIGH
1169  1169      1170  ...  PriCha         HIGH
1193  1193      1194  ...  Public         HIGH
1210  1210      1211  ...  PriCha         HIGH
1220  1220      1221  ...  PriCha         HIGH
1233  1233      1234  ...  PriCha         HIGH
1238  1238      1239  ...  Public         HIGH

[45 rows x 28 columns]

Most HIGH school with Grade 8 enrollment are 7-12 schools. One is a K-12 School

In [162]:
#Elementary Schools with 8+ enrollment, classify as K-8
sdfK12_filtered.loc[((sdfK12_filtered['SchoolLeve']=='HIGH') & (sdfK12_filtered['Grade8']>0)),'School_Level']='712'
sdfK12_filtered.loc[((sdfK12_filtered['SchoolLeve']=='HIGH') & (sdfK12_filtered['K']>0)),'School_Level']='K12'


display(sdfK12_filtered[((sdfK12_filtered['SchoolLeve']=='HIGH') & (sdfK12_filtered['Grade8']>0))])

       FID  OBJECTID  ...   Group School_Level
1        1         2  ...  Public          712
5        5         6  ...  PriCha          712
116    116       117  ...  PriCha          712
133    133       134  ...  Public          712
138    138       139  ...  Public          712
160    160       161  ...  Public          712
161    161       162  ...  Public          712
261    261       262  ...  Public          712
297    297       298  ...  Public          712
340    340       341  ...  Public          712
341    341       342  ...  Public          K12
351    351       352  ...  Public          712
359    359       360  ...  Public          712
408    408       409  ...  Public          712
428    428       429  ...  Public          712
459    459       460  ...  Public          712
529    529       530  ...  Public          712
542    542       543  ...  PriCha          712
587    587       588  ...  PriCha          712
605    605       606  ...  PriCha          712
622    622       623  ...  PriCha          712
664    664       665  ...  PriCha          712
725    725       726  ...  Public          712
741    741       742  ...  Public          712
744    744       745  ...  PriCha          712
745    745       746  ...  PriCha          712
817    817       818  ...  Public          712
820    820       821  ...  Public          712
821    821       822  ...  Public          712
840    840       841  ...  Public          712
871    871       872  ...  Public          712
872    872       873  ...  Public          712
924    924       925  ...  Public          712
992    992       993  ...  Public          712
993    993       994  ...  Public          712
1017  1017      1018  ...  PriCha          712
1155  1155      1156  ...  Public          712
1157  1157      1158  ...  PriCha          712
1164  1164      1165  ...  Public          712
1169  1169      1170  ...  PriCha          712
1193  1193      1194  ...  Public          712
1210  1210      1211  ...  PriCha          712
1220  1220      1221  ...  PriCha          712
1233  1233      1234  ...  PriCha          712
1238  1238      1239  ...  Public          712

[45 rows x 28 columns]

In [163]:
gradesums = sdfK12_filtered.groupby(['School_Level','Group'], as_index=False).agg(K  =('K'      ,'sum'),
                                                                       G01=('Grade1' ,'sum'),
                                                                       G02=('Grade2' ,'sum'),
                                                                       G03=('Grade3' ,'sum'),
                                                                       G04=('Grade4' ,'sum'),
                                                                       G05=('Grade5' ,'sum'),
                                                                       G06=('Grade6' ,'sum'),
                                                                       G07=('Grade7' ,'sum'),
                                                                       G08=('Grade8' ,'sum'),
                                                                       G09=('Grade9' ,'sum'),
                                                                       G10=('Grade10','sum'),
                                                                       G11=('Grade11','sum'),
                                                                       G12=('Grade12','sum'),
                                                                       Tot=('TotalK12','sum'))

display(gradesums)

   School_Level   Group      K    G01  ...    G10    G11    G12     Tot
0           712  PriCha      0      0  ...    980    923    758    5997
1           712  Public      0      0  ...   3157   3191   3096   13468
2          ELEM  PriCha   2216   2188  ...      0      0      0   13822
3          ELEM  Public  40640  42358  ...     82    104     84  289425
4          HIGH  PriCha      0      0  ...   1074   1095    960    3892
5          HIGH  Public      0      0  ...  43143  41626  39767  142254
6           K12  PriCha    878    909  ...    861    759    678   12030
7           K12  Public    475    400  ...    409    492   1155    5323
8            K8  PriCha   3077   3198  ...      0      0      0   28028
9            K8  Public    110    111  ...      1      5      1    1008
10          MID  PriCha      0      0  ...      0      0      0     408
11          MID  Public      0      0  ...      2      0      0  127765

[12 rows x 16 columns]

In [166]:
sdfK12_melt = pd.melt(sdfK12_filtered, id_vars=['FID','School_Level','Group','SHAPE'], value_vars=['K','Grade1','Grade2','Grade3','Grade4','Grade5','Grade6','Grade7','Grade8','Grade9','Grade10','Grade11','Grade12'])
sdfK12_melt = sdfK12_melt.rename(columns={"variable":"Grade","value":"Enrollment"})
sdfK12_melt

        FID School_Level  ...    Grade Enrollment
0         0         ELEM  ...        K        141
1         1          712  ...        K          0
2         2         ELEM  ...        K        160
3         3         HIGH  ...        K          0
4         4         HIGH  ...        K          0
...     ...          ...  ...      ...        ...
15010  1237          MID  ...  Grade12          0
15011  1238          712  ...  Grade12         43
15012  1239         ELEM  ...  Grade12          0
15013  1240         ELEM  ...  Grade12          0
15014  1241          K12  ...  Grade12          0

[15015 rows x 6 columns]

In [167]:
#create 'lookup table' for Enrollment Levelo

# initialize list of lists
data = [['ELEM','K'      ,'Elem'],
        ['ELEM','Grade1' ,'Elem'],
        ['ELEM','Grade2' ,'Elem'],
        ['ELEM','Grade3' ,'Elem'],
        ['ELEM','Grade4' ,'Elem'],
        ['ELEM','Grade5' ,'Elem'],
        ['ELEM','Grade6' ,'Elem'],
        ['ELEM','Grade7' ,'Elem'],
        ['ELEM','Grade8' ,'Elem'],
        ['ELEM','Grade9' ,'Elem'],
        ['ELEM','Grade10','Elem'],
        ['ELEM','Grade11','Elem'],
        ['ELEM','Grade12','Elem'],
        ['MID' ,'K'      ,'Midl'],
        ['MID' ,'Grade1' ,'Midl'],
        ['MID' ,'Grade2' ,'Midl'],
        ['MID' ,'Grade3' ,'Midl'],
        ['MID' ,'Grade4' ,'Midl'],
        ['MID' ,'Grade5' ,'Midl'],
        ['MID' ,'Grade6' ,'Midl'],
        ['MID' ,'Grade7' ,'Midl'],
        ['MID' ,'Grade8' ,'Midl'],
        ['MID' ,'Grade9' ,'Midl'],
        ['MID' ,'Grade10','Midl'],
        ['MID' ,'Grade11','Midl'],
        ['MID' ,'Grade12','Midl'],
        ['HIGH','K'      ,'High'],
        ['HIGH','Grade1' ,'High'],
        ['HIGH','Grade2' ,'High'],
        ['HIGH','Grade3' ,'High'],
        ['HIGH','Grade4' ,'High'],
        ['HIGH','Grade5' ,'High'],
        ['HIGH','Grade6' ,'High'],
        ['HIGH','Grade7' ,'High'],
        ['HIGH','Grade8' ,'High'],
        ['HIGH','Grade9' ,'High'],
        ['HIGH','Grade10','High'],
        ['HIGH','Grade11','High'],
        ['HIGH','Grade12','High'],
        ['K8'  ,'K'      ,'Elem'],
        ['K8'  ,'Grade1' ,'Elem'],
        ['K8'  ,'Grade2' ,'Elem'],
        ['K8'  ,'Grade3' ,'Elem'],
        ['K8'  ,'Grade4' ,'Elem'],
        ['K8'  ,'Grade5' ,'Elem'],
        ['K8'  ,'Grade6' ,'Elem'],
        ['K8'  ,'Grade7' ,'Midl'],
        ['K8'  ,'Grade8' ,'Midl'],
        ['K8'  ,'Grade9' ,'Midl'],
        ['K8'  ,'Grade10','Midl'],
        ['K8'  ,'Grade11','Midl'],
        ['K8'  ,'Grade12','Midl'],
        ['K12' ,'K'      ,'Elem'],
        ['K12' ,'Grade1' ,'Elem'],
        ['K12' ,'Grade2' ,'Elem'],
        ['K12' ,'Grade3' ,'Elem'],
        ['K12' ,'Grade4' ,'Elem'],
        ['K12' ,'Grade5' ,'Elem'],
        ['K12' ,'Grade6' ,'Elem'],
        ['K12' ,'Grade7' ,'Midl'],
        ['K12' ,'Grade8' ,'Midl'],
        ['K12' ,'Grade9' ,'Midl'],
        ['K12' ,'Grade10','High'],
        ['K12' ,'Grade11','High'],
        ['K12' ,'Grade12','High'],
        ['712' ,'K'      ,'Midl'],
        ['712' ,'Grade1' ,'Midl'],
        ['712' ,'Grade2' ,'Midl'],
        ['712' ,'Grade3' ,'Midl'],
        ['712' ,'Grade4' ,'Midl'],
        ['712' ,'Grade5' ,'Midl'],
        ['712' ,'Grade6' ,'Midl'],
        ['712' ,'Grade7' ,'Midl'],
        ['712' ,'Grade8' ,'Midl'],
        ['712' ,'Grade9' ,'Midl'],
        ['712' ,'Grade10','High'],
        ['712' ,'Grade11','High'],
        ['712' ,'Grade12','High']
       ]
  
# Create the pandas DataFrame
dfEnrollLevels = pd.DataFrame(data, columns = ['School_Level','Grade','Enrol_Levl'])
  
# print dataframe
dfEnrollLevels

   School_Level    Grade Enrol_Levl
0          ELEM        K       Elem
1          ELEM   Grade1       Elem
2          ELEM   Grade2       Elem
3          ELEM   Grade3       Elem
4          ELEM   Grade4       Elem
..          ...      ...        ...
73          712   Grade8       Midl
74          712   Grade9       Midl
75          712  Grade10       High
76          712  Grade11       High
77          712  Grade12       High

[78 rows x 3 columns]

In [173]:
#join to get enrollment levels
sdfK12_enrolllevels = pd.DataFrame.merge(sdfK12_melt,dfEnrollLevels,on=('School_Level','Grade'))
sdfK12_enrolllevels = sdfK12_enrolllevels.groupby(['FID','Group','Enrol_Levl'],as_index=False).agg(Enrol_Levl_Total=('Enrollment','sum'))
sdfK12_enrolllevels

       FID   Group Enrol_Levl  Enrol_Levl_Total
0        0  Public       Elem               903
1        1  Public       High              2208
2        1  Public       Midl               781
3        2  Public       Elem               903
4        3  Public       High                72
...    ...     ...        ...               ...
1359  1239  Public       Elem               404
1360  1240  Public       Elem               562
1361  1241  Public       Elem                 0
1362  1241  Public       High                 0
1363  1241  Public       Midl                 0

[1364 rows x 4 columns]

In [181]:
sdfK12_enrolllevels.dtypes

FID                  int64
Group               object
Enrol_Levl          object
Enrol_Levl_Total     int64
dtype: object

In [188]:
sdfK12_enrol = sdfK12_enrolllevels.pivot(index=['FID'], columns=['Group','Enrol_Levl'],values='Enrol_Levl_Total')

#collapse multi-index
sdfK12_enrol.columns = ['_'.join(col).strip() for col in sdfK12_enrol.columns.values]

sdfK12_enrol = sdfK12_enrol.fillna(0)

sdfK12_enrol = sdfK12_enrol.astype(int)

sdfK12_enrol = sdfK12_enrol[['Public_Elem','Public_Midl','Public_High','PriCha_Elem','PriCha_Midl','PriCha_High']]
sdfK12_enrol

      Public_Elem  Public_Midl  ...  PriCha_Midl  PriCha_High
FID                             ...
0             903            0  ...            0            0
1               0          781  ...            0            0
2             903            0  ...            0            0
3               0            0  ...            0            0
4               0            0  ...            0            0
...           ...          ...  ...          ...          ...
1237            0          976  ...            0            0
1238            0           14  ...            0            0
1239          404            0  ...            0            0
1240          562            0  ...            0            0
1241            0            0  ...            0            0

[1155 rows x 6 columns]

In [193]:
display(sdfK12_enrol.sum())
display(sdfK12_enrol.sum().sum())

Public_Elem    292581
Public_Midl    132908
Public_High    153754
PriCha_Elem     41981
PriCha_Midl     13345
PriCha_High      8851
dtype: int64

643420

In [ ]:
display(sdfK12_enrol.sum())